### ISSUE TITLE
Token in config for Xiaomi Smart Kettle

### ISSUE THREAD

**Issue by SchmDan** [Hypfer/Cybele#2]
Hey,

thanks for your great work! It's working like charm.
But wouldn't it be great to use the Xiaomi-App and Cybele at the same time? Therefore you need to extract the Token from the App and use it in Cybele. Also in the protocol documentation is this mentioned: https://github.com/aprosvetova/xiaomi-kettle#authentication
An option for specifying the token in the config would be great!

Thanks in advance!

**Comment by Hypfer** [comment]
There you go
