### ISSUE TITLE
Add support for yunmi.kettle.v12

### ISSUE THREAD

**Issue by tannisroot** [Hypfer/Cybele#21]
Hi, from what I can see, there's no support for yunmi.kettle.v12, otherwise known as Xiaomi Smart Kettle Pro.
What information can I provide to help with that?
Also, should note that when I wanted to try it anyway, I've encountered that the token format doesn't match what the format describe in documentation:
```
   ---------
   NAME:     Smart Kettle
   ID:       blt.6.1722869vcsk00
   BLE KEY:  be82a2c4dcd037e1f196d6810c0d5c62
   TOKEN:    97ca1089cf87e9163f11dbdd
   MODEL:    yunmi.kettle.v12
   ---------
```
(this is a BLE device so I don't really care if the token is public).

**Comment by RestOp** [comment]
I have got one the same in Spain. Also available in Germany. I think all over the Eupore.
Support is very needed!

Thanks!

**Comment by adamrzanek** [comment]
I would love them to be supported too. :)

**Comment by Japander** [comment]
Please add support for this device :)

**Comment by viotemp1** [comment]
Please add support for this device

**Comment by mirkokg** [comment]
I need testers:

https://github.com/mirkokg/mi_kettle_pro
