### ISSUE TITLE
Xiaomi / Viomi Mi Mija Smart Kettle v12

### ISSUE THREAD

**Issue by viotemp1** [Hypfer/Cybele#24]
Hi,

Any change to get it working with
   NAME:     Mi Smart Kettle Pro
   MODEL:    yunmi.kettle.v12

**Comment by Marcusg562** [comment]
I‘ve the same issue. My config seems ok 
![AEC7D233-7288-4FAD-9D37-5D0022C888BB](https://user-images.githubusercontent.com/105149/147378281-54ce9f31-b68b-426d-8933-dca2a424a2d2.jpeg)

But the Cybele doesn‘t start:
![AC214B11-AA9E-4D2F-9347-0C92CEEB4175](https://user-images.githubusercontent.com/105149/147378282-aba490bb-2748-4905-b0d0-a2250e0822a4.jpeg)

**Comment by Hypfer** [comment]
#21 
#20
