### ISSUE TITLE
Support for Mi Xiaomi Mijia LYWSD03MMC Bluetooth 4.2 Temperature Humidity sensor ?

### ISSUE THREAD

**Issue by RingoAl** [Hypfer/Cybele#9]
Hello.
Is there any way to add Xiaomi Mijia LYWSD03MMC Bluetooth 4.2 Temperature Humidity sensor (LYWSD03MMC) ?
I have found [Python script](https://github.com/JsBergbau/MiTemperature2) which can get readings from it, but it is not working simultaneously with Cybele.
Thanks.

**Comment by charlie-cheetah** [comment]
I've added support for it in my fork: https://github.com/charlie-cheetah/Cybele/tree/Mijia_LYWSD03MMC

**Comment by RingoAl** [comment]
> I've added support for it in my fork: https://github.com/charlie-cheetah/Cybele/tree/Mijia_LYWSD03MMC

Thanks. I will try it later.
